import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 42/255, green: 100/255, blue: 97/255, opacity: 1), width: 2) 
    }

    func borderBoardeer2() -> some View {
        return self.border(Color(.sRGB, red: 202/255, green: 129/255, blue: 129/255, opacity: 1), width: 1) 
    }

    func borderRadius() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func border4Token() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderEmplifi() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderMistetemo() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken7() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderName() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken9() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderName() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken10() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken11() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken12() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderNewAnme() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken13() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderMoodys() -> some View {
        return self.border(Color(.sRGB, red: 202/255, green: 129/255, blue: 129/255, opacity: 1), width: 1) 
    }

    func borderToken14() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken15() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken16() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken17() -> some View {
        return self.border(Color(.sRGB, red: 111/255, green: 31/255, blue: 31/255, opacity: 1), width: 4) 
    }

    func borderToken18() -> some View {
        return self.border(Color(.sRGB, red: 218/255, green: 36/255, blue: 36/255, opacity: 1), width: 4) 
    }

    func borderToken19() -> some View {
        return self.border(Color(.sRGB, red: 226/255, green: 113/255, blue: 113/255, opacity: 1), width: 4) 
    }

    func borderToken20() -> some View {
        return self.border(Color(.sRGB, red: 221/255, green: 63/255, blue: 63/255, opacity: 1), width: 5) 
    }

    func borderToken21() -> some View {
        return self.border(Color(.sRGB, red: 224/255, green: 61/255, blue: 61/255, opacity: 1), width: 5) 
    }

    func borderToken22() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken23() -> some View {
        return self.border(Color(.sRGB, red: 196/255, green: 71/255, blue: 71/255, opacity: 1), width: 5) 
    }

    func borderMlb() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 4) 
    }

    func borderToken24() -> some View {
        return self.border(Color(.sRGB, red: 189/255, green: 91/255, blue: 91/255, opacity: 1), width: 5) 
    }

    func borderToken25() -> some View {
        return self.border(Color(.sRGB, red: 234/255, green: 129/255, blue: 129/255, opacity: 1), width: 6) 
    }

    func borderToken26() -> some View {
        return self.border(Color(.sRGB, red: 219/255, green: 99/255, blue: 99/255, opacity: 1), width: 4) 
    }

    func borderToken27() -> some View {
        return self.border(Color(.sRGB, red: 76/255, green: 50/255, blue: 50/255, opacity: 1), width: 5) 
    }

    func borderToken28() -> some View {
        return self.border(Color(.sRGB, red: 175/255, green: 90/255, blue: 90/255, opacity: 1), width: 6) 
    }

    func borderToken29() -> some View {
        return self.border(Color(.sRGB, red: 206/255, green: 142/255, blue: 142/255, opacity: 1), width: 6) 
    }

    func borderToken30() -> some View {
        return self.border(Color(.sRGB, red: 147/255, green: 76/255, blue: 76/255, opacity: 1), width: 5) 
    }

    func borderLaPoste() -> some View {
        return self.border(Color(.sRGB, red: 172/255, green: 91/255, blue: 91/255, opacity: 1), width: 10) 
    }

    func borderSdWorx() -> some View {
        return self.border(Color(.sRGB, red: 208/255, green: 76/255, blue: 76/255, opacity: 1), width: 5) 
    }

    func borderAbbott() -> some View {
        return self.border(Color(.sRGB, red: 193/255, green: 100/255, blue: 100/255, opacity: 1), width: 5) 
    }

    func borderName() -> some View {
        return self.border(Color(.sRGB, red: 211/255, green: 96/255, blue: 96/255, opacity: 1), width: 4) 
    }

    func borderName() -> some View {
        return self.border(Color(.sRGB, red: 181/255, green: 53/255, blue: 53/255, opacity: 1), width: 3) 
    }

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 193/255, green: 79/255, blue: 79/255, opacity: 1), width: 4) 
    }

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 40/255, green: 27/255, blue: 27/255, opacity: 1), width: 5) 
    }

    func borderName() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderEy4() -> some View {
        return self.border(Color(.sRGB, red: 218/255, green: 100/255, blue: 100/255, opacity: 1), width: 6) 
    }

    func borderToken31() -> some View {
        return self.border(Color(.sRGB, red: 246/255, green: 11/255, blue: 11/255, opacity: 1), width: 3) 
    }

    func borderBellBoarder() -> some View {
        return self.border(Color(.sRGB, red: 195/255, green: 102/255, blue: 102/255, opacity: 1), width: 4) 
    }

    func borderLaPosteBoarder() -> some View {
        return self.border(Color(.sRGB, red: 190/255, green: 128/255, blue: 128/255, opacity: 1), width: 3) 
    }

    func borderFossBoarder() -> some View {
        return self.border(Color(.sRGB, red: 212/255, green: 33/255, blue: 33/255, opacity: 1), width: 5) 
    }

    func borderToken32() -> some View {
        return self.border(Color(.sRGB, red: 158/255, green: 70/255, blue: 70/255, opacity: 1), width: 5) 
    }

    func borderToken33() -> some View {
        return self.border(Color(.sRGB, red: 207/255, green: 90/255, blue: 90/255, opacity: 1), width: 5) 
    }

    func borderToken34() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 3) 
    }
}