import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    func textStyleH1() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 57))
    }

    func textStyleH2() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 43))
    }

    func textStyleH3() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 32))
    }

    func textStyleH4() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 24))
    }

    func textStyleH5() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 21))
    }

    func textStyleLargeLead() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 24))
    }

    func textStyleMediumLead() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 21))
    }

    func textStyleButtonLabel() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 21))
    }

    func textStyleParagraph() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 18))
    }

    func textStyleSmallParagraph() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 16))
    }

    func textStyleTinyParagraph() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 12))
    }

    func textStyleSupernova() -> some View {
        return self
            .font(Font.custom("Roboto-Regular", size: 16))
            .underline() 
    }

    func textStyleNewTyp() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleBellTypo() -> some View {
        return self
            .font(Font.custom("Abel-regular", size: 10))
            .underline() 
            .textCase(.uppercase) 
    }

    func textStyleLaPosteTypo() -> some View {
        return self
            .font(Font.custom("Aboreto-regular", size: 10))
            .underline() 
            .textCase(.uppercase) 
    }

    func textStyleFossTypo() -> some View {
        return self
            .font(Font.custom("Acme-regular", size: 10))
            .underline() 
    }

    func textStyleTestNewTypo() -> some View {
        return self
            .font(Font.custom("Abel-regular", size: 10))
            .strikethrough() 
            .textCase(.uppercase) 
    }
}
