import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {  

    func borderRadiusToken() -> some View {
        return self.cornerRadius(6) 
    }

    func borderRd() -> some View {
        return self.cornerRadius(10) 
    }
}