import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {  

    func borderToken1() -> some View {
        return self.cornerRadius(4) 
    }

    func borderWrike() -> some View {
        return self.cornerRadius(4) 
    }

    func borderNewOne() -> some View {
        return self.cornerRadius(4) 
    }

    func borderToken4() -> some View {
        return self.cornerRadius(4) 
    }

    func borderNewToken() -> some View {
        return self.cornerRadius(4) 
    }

    func borderName() -> some View {
        return self.cornerRadius(4) 
    }

    func borderToken5() -> some View {
        return self.cornerRadius(7) 
    }
}